# Generated by Django 4.1 on 2024-03-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_product_vendor_product_user_delete_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=0, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
